### PR TITLE
extrapolation examples

### PR DESCRIPTION
**Pull request by hoangxuyenle**
-update downloads.py (adding function to download test file from github)
-Adding 2 examples for extrapolation (stress for 3d-element and strain result for 2d-element)

### CODE REVIEW

**Comment by hoangxuyenle** [comment]
@cbellot000

**Comment by cbellot000** [comment]
@hoangxuyenlecan you please look in the style checking (under "checks") you will see that you have some spelling mistakes that you can fix

**Comment by cbellot000** [comment]
Hi @akaszynski, do you know why the azure pipelines are not launched on this PR? Is it an authorization issue?

**Review by cbellot000 — APPROVED** [review]

**Comment by akaszynski** [comment]
> Hi @akaszynski, do you know why the azure pipelines are not launched on this PR? Is it an authorization issue?

Exactly that.  Our PRs won't run from external forks it seems.

**Comment by akaszynski** [comment]
Actually, add this in:
```

pr:
  branches:
    include:
    - '*'
    exclude:
    - '*no-ci*'

```

**Comment by cbellot000** [comment]
@akaszynski where should we put this piece of code?

**Comment by akaszynski** [comment]
Extend our existing triggers in our CI:
https://github.com/pyansys/DPF-Core/blob/a529380470ad851b93fe2d9bebf771331c6c6302/.ci/azure-pipelines.yml#L18-L21

**Comment by akaszynski** [comment]
Appears that our CI just won't run on external forks.  I'm inviting you to be a collaborator.  Once you've joined, just clone this repo and make a branch directly on it.

**Pull request closed without merging**
