### PR TITLE
Format core files with black

### PR DESCRIPTION
**Pull request by jleonatti**
This is the first of several PRs containing black formatting. This PR formats the ansys/dpf/core directory, excluding the operators.

### CODE REVIEW

**Comment by jleonatti** [comment]
Sorry to bug you, but could someone review this please? @cbellot000 @anslpa @rlagha I am waiting for this to merge before formatting the next set of files.

**Review by cbellot000 — APPROVED** [review]

**Comment by anslpa** [comment]
@jleonatti Will the tests folder be reviewed the same way ?

**Review by anslpa — APPROVED** [review]

**Comment by jleonatti** [comment]
> @jleonatti Will the tests folder be reviewed the same way ?

@anslpa yes that is the plan. Is that okay or do you want them to be skipped?

**Comment by jleonatti** [comment]
> @jleonatti It is totally ok and I think this is needed (I was just wondering).


Okay great. I will get to them in one of the next few PRs.

**Pull request merged**
